### PR TITLE
Added Docker container capability

### PR DESCRIPTION
**Pull request by bmamlin**
I added the ability to build a Docker container from this repo along with instructions on how to easily get it up and running.

Cheers,

-Burke

### CODE REVIEW

**Comment by jonathandick** [comment]
Cool. Thanks Burke.

On Thu, Mar 3, 2016 at 6:24 AM, Burke Mamlin <notifications@github.com>
wrote:

> I added the ability to build a Docker container from this repo along with
> instructions on how to easily get it up and running.
>
> Cheers,
>
> -Burke
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/AMPATH/etl-rest-server/pull/79
> Commit Summary
>
>    - Added Docker container capability
>
> File Changes
>
>    - *A* .dockerignore
>    <https://github.com/AMPATH/etl-rest-server/pull/79/files#diff-0> (3)
>    - *A* Dockerfile
>    <https://github.com/AMPATH/etl-rest-server/pull/79/files#diff-1> (21)
>    - *M* README.md
>    <https://github.com/AMPATH/etl-rest-server/pull/79/files#diff-2> (53)
>    - *A* docker-compose.yml
>    <https://github.com/AMPATH/etl-rest-server/pull/79/files#diff-3> (15)
>    - *A* settings.js
>    <https://github.com/AMPATH/etl-rest-server/pull/79/files#diff-4> (13)
>
> Patch Links:
>
>    - https://github.com/AMPATH/etl-rest-server/pull/79.patch
>    - https://github.com/AMPATH/etl-rest-server/pull/79.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AMPATH/etl-rest-server/pull/79>.
>



-- 
Jonathan Dick, MD
Chief Medical Information Officer, AMPATH
Assistant Professor of Clinical Medicine, IU School of Medicine
Research Scientist, Regenstrief Institute Inc.

**Comment by mhawila** [comment]
Thanks @bmamlin for the effort. Unfortunately I am running into an error when running "docker-compose up -d". The error is as shown below.

> Unsupported config option for services service: 'mysql4etl'

I am doing this on Mac.

**Comment by bmamlin** [comment]
what do you see from this command?

    docker-compose -v

**Comment by mhawila** [comment]
Sorry @bmamlin I didn't see your comment sooner. Running "docker-compose -v" gives the following output.
docker-compose version: 1.4.0

**Comment by mhawila** [comment]
@bmamlin I have installed docker-compose 1.6.2 and now I am getting

Creating network "etlrestserver_default" with the default driver
ERROR: 404 page not found

I haven't tried to debug though.

**Comment by bmamlin** [comment]
@mhawila, I'm happy to debug for you. When get a moment, do this for me:

Open a terminal, go to a folder with this pull request's code, and clear the terminal history.
 ```bash
git clone https://github.com/AMPATH/etl-rest-server.git
cd etl-rest-server
git fetch origin pull/79/head:docker
git checkout docker
⌘K
```
Then, run the following four commands†, copy your terminal history into paste.bin, and reply with the link to the paste.bin entry.
```bash
docker-compose up -d
curl -k https://docker:8002
docker ps -a | grep etl
docker images | grep etl
```

Thanks!

† I'm assuming you have "docker" pointing to your docker machine's IP address in /etc/hosts, if not replace "docker" in the CURL command with the IP address of your docker machine (from `docker-machine ip default`)

**Comment by bmamlin** [comment]
@mhawila, let me make it even easier...

Save [this script](https://gist.github.com/bmamlin/cba2972a363a512b9dd0/raw/5d80ae60a89f635a0b6870bc9ac7af7890e83837/etl-pull-79.sh) into `etl-pull-79.sh`, chmod 755, and then run the script. It will do all the work for you and spit out a link to send me.

**Comment by mhawila** [comment]
Turns out I need to upgrade my docker machine to 1.10+ as well. I will be doing that and see how it goes.

Thanks.

**Comment by bmamlin** [comment]
Download & install [Docker Toolbox](https://www.docker.com/products/docker-toolbox) it takes care of all Docker tools for you (docker-machine, docker-compose, and docker) and will get you up to the latest version for each.

**Comment by mhawila** [comment]
@burke I have actually been trying to run the command "docker-compose up -d" with the right versions for quite some time now. Unfortunately it just hangs at some point. It appears to be a network issue because it happens when attempting to download mysql image. I thought I should let you know. Below is a screen that is displayed in every attempt I have done so far.

➜  etl-rest-server git:(burke-docker) docker-compose up -d
Pulling mysql4etl (mysql:latest)...
latest: Pulling from library/mysql
fdd5d7827f33: Pulling fs layer
a3ed95caeb02: Download complete
2d9b55a37647: Download complete
9964041ec782: Download complete
f3e6609e3bc3: Retrying in 1 seconds
15e1bcfe2437: Download complete
16eea8ab42c7: Download complete
3ebb6d314aee: Waiting
ed7cc70659fd: Waiting
5003cda816ca: Waiting

**Comment by mhawila** [comment]
I will try to sort out the network problems and see how it goes.

**Comment by bmamlin** [comment]
@mhawila, I've seen a networking issue with docker machines, especially when working on a laptop and switching networks (the DNS settings in the container's `/etc/resolve.conf` is not updated properly). From what I've read, this may be a VirtualBox issue as much as Docker. I hope they get it fixed. Anyway, you can quickly fix it by restarting the machine:

```bash
# Restart docker machine
docker-machine restart

# Make sure environment is updated if necessary after restart
eval $(docker-machine env)
```

Anytime I've encountered a networking problem with Docker, it's because I have switched networks (moved around with my laptop) and restarting the docker machine fixes the problem. If you're working with containers that you keep running in the background, another option is to put "8.8.8.8" in `/etc/resolve.conf` on those containers. So far, I've gotten by with just restarting the docker machine if/when I re-encounter the networking issue. Now that I know it's changing networks (e.g., moving from work to home), I've begun to anticipate it.

**Pull request closed without merging**
